### ISSUE TITLE
几个主流平台都不能用呢

### ISSUE THREAD

**Issue by putianhui** [wujunwei928/parse-video#1]
微视短视频，西瓜视频，最右，梨视频，快手
这几个平台老哥不能用呢

**Comment by wujunwei928** [comment]
@putianhui  麻烦提供下测试的分享链接

**Comment by putianhui** [comment]
> @putianhui 麻烦提供下测试的分享链接

微视
```bash
https://isee.weishi.qq.com/ws/app-pages/share/index.html?wxplay=1&id=7ysBGpEfo1OoWtewM&spid=3585289207762062551&qua=v1_iph_weishi_8.79.0_209_app_a&chid=100081014&pkg=3670&attach=cp_reserves3_1000370011
```

西瓜
```bash
https://v.ixigua.com/6dXWJaF/
```
最右
```bash
https://share.xiaochuankeji.cn/hybrid/share/post?pid=282102599&zy_to=applink&share_count=1&m=9e1e2e259b77404d4807381c58df66d3&d=6db94c6d1fd9872600360c3851d4aba89b6644fa67b482f288e273c508a83c33449ec40c51404fdc138b01fcd681c4d9&app=zuiyou&recommend=r0&name=n0&title_type=t0
```

梨视频
```bash
https://www.pearvideo.com/detail_1028073
```

快手
```bash
https://v.kuaishou.com/tCRYt8
```

**Comment by putianhui** [comment]
@wujunwei928 视频在上方

**Comment by wujunwei928** [comment]
1. 西瓜, 最右, 快手不同视频的链接返回信息可能不一致, 兼容了您提供的这几个地址的返回
2. 微视本身解析是支持的, demo中url正则表达式解析微视分享链接时有问题, 已兼容
3. 梨视频我这看时支持的, 只是接口没有标题信息
@putianhui  我这边看可以了,  可以再试下, 看是否还有问题;  如果没有问题了,  也辛苦回复下, 我这边关下issue

**Comment by putianhui** [comment]
@wujunwei928 老哥我这边试其他平台都可以了，但是微视demo页面能解析视频，我调用接口解析就会失败呢

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/68322685/188311611-4fc70e63-e606-431f-9c31-6370f4c8bfe4.png">

**Comment by wujunwei928** [comment]
@putianhui 因为微视的分享链接比较复杂, 含有?, &等特殊字符, 需要先进行url转义, 否则会参数解析会有问题,  转义后的格式类似: http://127.0.0.1:8080/video/share/url/parse?url=https%3A%2F%2Fisee.weishi.qq.com%2Fws%2Fapp-pages%2Fshare%2Findex.html%3Fwxplay%3D1%26id%3D7ysBGpEfo1OoWtewM%26spid%3D3585289207762062551%26qua%3Dv1_iph_weishi_8.79.0_209_app_a%26chid%3D100081014%26pkg%3D3670%26attach%3Dcp_reserves3_1000370011

**Comment by putianhui** [comment]
@wujunwei928 好的老哥，我给你点个star
