### ISSUE TITLE
很多视频提示not have source config,但是本身是能打开播放的

### ISSUE THREAD

**Issue by goxofy** [wujunwei928/parse-video#27]
https://www.huya.com/video/play/954247170.html
https://www.ixigua.com/7326118558897799715
https://www.kuaishou.com/short-video/3xcg9ui55ppvqk2
例如这种

**Comment by wujunwei928** [comment]
看链接应该都是电脑端链接，请尽量使用app分享链接, 电脑网页版未做测试，readme中有介绍
