### ISSUE TITLE
解析无效

### ISSUE THREAD

**Issue by corestudi0** [wujunwei928/parse-video#35]
![Screenshot_20240609_140855](https://github.com/wujunwei928/parse-video/assets/102907913/13afa220-827e-490f-b120-96975d5bdbde)
输入值：http://xxxxxxxx:10808/video/share/url/parse?url=https://v.kuaishou.com/BOOASx
返回值：
{
  "code": 200,
  "msg": "解析成功",
  "data": {
    "author": {
      "uid": "",
      "name": "",
      "avatar": ""
    },
    "title": "",
    "video_url": "",
    "music_url": "",
    "cover_url": "",
    "images": []
  }
}

**Comment by wujunwei928** [comment]
![image](https://github.com/wujunwei928/parse-video/assets/3396697/9dfff4aa-b7fb-4036-aa45-cc264062254a)

我这看解析没问题, 重新试下看看, 确认下使用的代码是不是最新的

**Comment by Jeoican** [comment]
![image](https://github.com/wujunwei928/parse-video/assets/42536930/20ae20b4-2f66-4f50-9bce-603ff118c01f)
快手解析会出现解析成功但无链接（抖音没问题，其他平台没试）

**Comment by wujunwei928** [comment]
快手同一个链接, 有时正常返回, 有时会返回异常状态值, 类似{"result":2,"error_msg":null,"request_id":"719732967210634356"}     
已添加异常状态值判断
