### ISSUE TITLE
快手解析错误，返回[2001] antispam need captcha

### ISSUE THREAD

**Issue by siyunxing** [wujunwei928/parse-video#36]
{
  result: 2001,
  error_msg: '[2001] antispam need captcha',
  request_id: '718853582640944593',
  captchaConfig: '{"type":1,"url":"https://captcha.zt.kuaishou.com/rest/zt/captcha/sliding/config","captchaSession":"Cgp6dC5jYXB0Y2hhEsECNb4fOrbLKbZmxIIsmqQI1aQayPc-fmvgohU1rpo2NoeI5BjJTZHk30mpO5I4HXzbGqLuBv9zK_nTdlXUvoGPjAJ1tqEp9srf-EEuaemgzhq0V4nCSBVrlr8KJ7Ys0Co1_Qc0czf6ycF09fbqLyluXy6DXZH_yNRUvLhiBhdIzovx9W8iqJ1OKz1OkBnkUbBiirnf74_nb-N0cR53gdHXSo-1JriyfWl_oogAaQi17o7Zv1ulz4Qog6KGzWKrBEvpr4BNy48Ev-F3glxcR9XVHTb0QJTVe7ckyMztw4gloQnW3z7ZB-nHgu_v6fsJLRKlm7bL1uVxkQj3F3HBhTSM7P7z01a70fseuKp3qRfI4fgEK4orkAkCp8QYk-j2b5FzJFLDhVBVriXLEDtjV-BBfrJT731HHKnp3zHjjlSczfb4GhIX6csOoirK9qqQy-JPOXCR8nooBTAC","jsSdkUrl":"https://ali2.a.yximgs.com/static/captcha/sdk/kwaiCaptcha.bffe9a4c.umd.min.js","bizName":"DEFAULT"}'
}

这是快手返回的信息

**Comment by wujunwei928** [comment]
看错误像出现验证码了, 估计是请求太频繁, ip被限制了
