### ISSUE TITLE
抖音似乎不能用了

### ISSUE THREAD

**Issue by xisuo67** [wujunwei928/parse-video#39]
抖音似乎不能用了，刚把代码拉下来运行，试了几个链接都不行
![image](https://github.com/wujunwei928/parse-video/assets/22284363/25455db6-2820-42df-b532-cd3303f5c450)

## 抖音链接
> 8.23 复制打开抖音，看看【潇湘晨报的作品】山东青岛。男子下车后忘记拉手刹，钓完鱼回来发现车已... https://v.douyin.com/i6mWxaXW/ 12/08 Q@K.Wm JVl:/

**Comment by wujunwei928** [comment]
![image](https://github.com/wujunwei928/parse-video/assets/3396697/94ecbf6c-22de-457d-89e0-1529485547df)
我这看没问题, 检查下自己网络, 打开浏览器开发者工具, 看下接口返回

**Comment by xisuo67** [comment]
![image](https://github.com/wujunwei928/parse-video/assets/22284363/4df400b7-1c0f-4a3c-accc-1d740fc0de3f)
解析是没问题的，点击下载跳转地址404

**Comment by Aristokun** [comment]
我这边用题主给出的视频链接测试 一切正常     网页和api都可以通    尝试pull一下新版？ 你看你的下载url也和版主不一致       https://v3-dy-o.zjcdn.com/b5900b5bda21d57663459b219f8b4fad/668656a1/video/tos/cn/tos-cn-ve-15/okGaerZkKAfsB2A5AAsxDN0Y74veCezgCDE4Pi/?a=1128&br=2828&bt=2828&btag=c0010e00090000&cc=1f&cd=0%7C0%7C0%7C0&ch=0&cquery=100y&cr=0&cs=0&cv=1&dr=0&ds=3&dy_q=1720076406&dy_va_biz_cert=&feature_id=f0150a16a324336cda5d6dd0b69ed299&ft=tFF4488-oLsD12NWeX_T-UxiMYy5gF_O51Y&l=20240704150006086FCFD7A12E0404EEBD&mime_type=video_mp4&qs=0&rc=ZDMzPDtoMzw6Nzs5O2lnNEBpM2VzOWw5cjp2dDMzNGkzM0AxYC1hYzEwXzAxNC4wYTUzYSNvLWtsMmRrby5gLS1kLWFzcw%3D%3D&req_cdn_type=

**Comment by xisuo67** [comment]
我仔细对比了一下接口返回数据，初步判断，应该是被转义以后导致连接访问问题，以下是我提供的排查过程
>采集地址：4.69 b@a.At cNj:/ 04/06 # 纯欲天花板 # 美女热舞🔥 # 甜妹 # 清纯甜美  https://v.douyin.com/i6xDkwAp/ 复制此链接，打开Dou音搜索，直接观看视频！
![image](https://github.com/wujunwei928/parse-video/assets/22284363/d97eac10-4d2b-4f5a-a989-b8cf9a98d9ca)
以上是界面效果
- 通过抓取接口返回结构如下：
![image](https://github.com/wujunwei928/parse-video/assets/22284363/03c085ea-bc1f-4cfe-a70f-954f9a753b2d)

## 接口返回
```
{
    "code": 200,
    "msg": "解析成功",
    "data": {
        "author": {
            "uid": "MS4wLjABAAAAGSOtiMJdERRboevcTSLs7S-A5MAAElCODnBgTXJPtk84nmTLbMxya22T5FebQcnQ",
            "name": "甜甜的圈圈",
            "avatar": "https://p11.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-i-0813c001_o0NnpANADAgAIJegmvVA1YWbCCR9CbAGZEAkqe.jpeg?from=327834062"
        },
        "title": "#纯欲天花板 #美女热舞🔥 #甜妹 #清纯甜美",
        "video_url": "https://v26-cold.douyinvod.com/7f1473c9f25ed4fba369b7e317f48b94/668654a2/video/tos/cn/tos-cn-ve-15c001-alinc2/oYBDAqkP6iZBsAlQIziBwLf7Eo51gPkJAN81De/?a=1128\u0026ch=0\u0026cr=0\u0026dr=0\u0026cd=0%7C0%7C0%7C0\u0026cv=1\u0026br=1728\u0026bt=1728\u0026cs=0\u0026ds=3\u0026ft=rVQ6egwwZRnTseDo1PDS6kFgAX1tG-MM2f9eFGeoqqV12nzXT\u0026mime_type=video_mp4\u0026qs=0\u0026rc=ZzM7ZTY5NzRoaGRnMzo6ZUBpajdqNWo5cnRkczMzNGkzM0BeMWAwYGBjXmMxXl4yNi0uYSNxNGBqMmRzY3JgLS1kLWFzcw%3D%3D\u0026btag=80010e00088000\u0026cquery=100y\u0026dy_q=1720075915\u0026feature_id=f0150a16a324336cda5d6dd0b69ed299\u0026l=202407041451556FBCA0A12012B603A43A",
        "music_url": "",
        "cover_url": "https://p26-sign.douyinpic.com/tos-cn-i-0813/oogAuEYdmAAUHiy3ADCnEgegFA5INQf9OA9lDa~c5_300x400.webp?x-expires=1721282400\u0026x-signature=xTLaKpe%2FYeYHQGK7%2BbZ6Iq5E5vg%3D\u0026from=327834062_large\u0026s=PackSourceEnum_DOUYIN_REFLOW\u0026se=false\u0026sc=cover\u0026biz_tag=aweme_video\u0026l=20240704145155DE5C567B1A03B203B8D7",
        "images": []
    }
}
```
## 过程
> 通过返回数据。直接复制**video_url**对象，在浏览器可以访问，复制***cover_url**对象链接，无法访问，和界面正好相反

> 从返回链接来看，有部分转移字符串，可能导致直接前端url，在赋值a标签的时候，导致转义错误，无法正确访问！作者可以试试这个链接

**Comment by xisuo67** [comment]
## 补充一下
> 通过文件对比，界面上能正常访问的封面地址，和接口返回的cover_url地址，格式确实有所改变
![image](https://github.com/wujunwei928/parse-video/assets/22284363/506398cd-6b4a-47c6-b281-56997ac22b0a)

希望能对作者有所帮助

**Comment by Aristokun** [comment]
我刚才发的url  是单击下载视频后复制的url   和后台curl返回的一致 我们用的同一个视频id  不该出现转义不同

**Comment by Aristokun** [comment]
![image](https://github.com/wujunwei928/parse-video/assets/89496481/42d8f940-b2e4-4adb-9986-8795c7001763)
你看 api返回的video_url 域名并不一致    你确定你的版本没有问题吗

**Comment by Aristokun** [comment]
我没用网页端  刚才发现403其实作者在温馨提示中标注了...

**Comment by xisuo67** [comment]
我发现一个很奇怪的现象，直接点击链接跳转，没有问题，在a标签内，跳转，却会提示403
![image](https://github.com/wujunwei928/parse-video/assets/22284363/207593cf-23ef-4d96-93b1-d459dbd7c993)

**Comment by Aristokun** [comment]
![image](https://github.com/wujunwei928/parse-video/assets/89496481/438eecb9-2fd1-4e28-aa9f-211923a8ab8d)

**Comment by Aristokun** [comment]
这个是服务器对请求来源进行了限制   在另一个issues里有解答    #38

**Comment by rucswax** [comment]
好像添加一个属性 referrerpolicy 就可以了
原：
https://github.com/wujunwei928/parse-video/blob/5590cb2a08946e346becc66be8151e06ec76afb4/templates/index.tmpl#L115-L120

改：
```html
        successHtml += '<a class="mdui-btn mdui-btn-raised" href="'+jsonObj.data.cover_url+'" target="_blank" download="video" referrerpolicy="no-referrer" >下载封面</a>';

        // 如果video_url不为空, 则显示下载视频按钮
        if(jsonObj.data.video_url != ""){
            successHtml += '<a class="mdui-btn mdui-btn-raised" href="'+jsonObj.data.video_url+'" target="_blank" download="video" referrerpolicy="no-referrer" >下载视频</a>';
        }
```

**Comment by wujunwei928** [comment]
@rucswax 添加 属性 referrerpolicy 方法不错 👍, 已添加进代码
