### ISSUE TITLE
抖音这种链接不支持。

### ISSUE THREAD

**Issue by xiaochaodada** [wujunwei928/parse-video#41]
链接：https://www.iesdouyin.com/share/video/7371419627584326947/
我在代码加了iesdouyin.com域名，但是解析成功返回：{
  "code": 200,
  "msg": "解析成功",
  "data": null
}   
data 是null

**Comment by wujunwei928** [comment]
只在 parser/vars.go 添加域名不行，需要在对应的解析器 parser/douyin.go 中添加对应域名的解析 

在最新版 [a03348978](https://github.com/wujunwei928/parse-video/commit/a03348978f89935ff555cda39933d69b988ef857) 已支持电脑网页端链接
