### ISSUE TITLE
微博视频号右上角水印无法去除

### ISSUE THREAD

**Issue by yanghouqing** [wujunwei928/parse-video#42]
https://weibo.com/tv/show/1034:5056161490075775

**Comment by yanghouqing** [comment]
我看很多小程序已支持拿到无印视频，他们的视频链接开头是https://ad.video.weibocdn.com这个域名，我找来找去找不到，求大佬解决

**Comment by yanghouqing** [comment]
我看很多小程序已支持拿到无印视频，他们拿到的无水印视频链接开头是https://ad.video.weibocdn.com这个域名，我找来找去找不到，求大佬解决

**Comment by wujunwei928** [comment]
应该是源视频就带水印, 我找个无水印的试下, 是可以的: https://weibo.com/tv/show/1034:5063117600915473?from=old_pc_videoshow

**Comment by yanghouqing** [comment]
> 应该是源视频就带水印, 我找个无水印的试下, 是可以的: https://weibo.com/tv/show/1034:5063117600915473?from=old_pc_videoshow

是微博放回出来视频把水印带上去了，现在有一些小程序能拿到那个不带水印视频的链接，
