### ISSUE TITLE
部署服务后， 快手响应200，但接口返回异常, 本地localhost:8080 没问题。

### ISSUE THREAD

**Issue by yaogengzhu** [wujunwei928/parse-video#45]
<img width="455" alt="Clipboard_Screenshot_1725511917" src="https://github.com/user-attachments/assets/dc06ee19-b9bf-46b8-834c-cfa247b19708">

**Comment by wujunwei928** [comment]
可以打断点, 看下返回的详细信息是什么

**Comment by 2857584289** [comment]
{"result":50,"ab8d":true,"error_msg":"签 名验证失败"}，快手接口返回这个好像不行了

**Comment by guilairengshishaonian** [comment]
签名验证失败了

**Comment by wujunwei928** [comment]
快手解析已修复, 详情: [026197](https://github.com/wujunwei928/parse-video/commit/e8bd8bfe3fa245cff8755dc12f515148fa026197)
