### ISSUE TITLE
解析快手链接返回201

### ISSUE THREAD

**Issue by ACSN5** [wujunwei928/parse-video#46]
![image](https://github.com/user-attachments/assets/76fb49db-374c-43d2-8e38-c6bfc436e438)
视频链接：https://www.kuaishou.com/short-video/3x24h4gjvevux4w
返回值：
```
{
    "code": 201,
    "msg": "share url [https://www.kuaishou.com/short-video/3x24h4gjvevux4w] not have source config",
    "data": null
}

```
尝试过抖音，抖音可以解析，快手不行

**Comment by wujunwei928** [comment]
快手不支持pc连接, 请使用app分享链接, 类似 https://v.kuaishou.com/xxx
