### ISSUE TITLE
快手上博主未设置限制下载的作品解析下载不了

### ISSUE THREAD

**Issue by KabourWu** [wujunwei928/parse-video#48]
快手上博主未设置限制下载的作品解析下载不了

**Comment by KabourWu** [comment]
py版本可以下载博主无限制的视频作品，但是不能解析下载无限制的图集作品

**Comment by wujunwei928** [comment]
可以提供下不能解析的视频和图集链接

**Comment by KabourWu** [comment]
> 可以提供下不能解析的视频和图集链接

https://v.kuaishou.com/2vM4eP

**Comment by wujunwei928** [comment]
我看能解析呀, 就一张图片, 没有视频
